name: progresssystem_splashscreen
version: 1.0.0+1

environment:
   sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
      - assets/images/
      - assets/images/dashboard/
      - assets/images/splash_images/
      - assets/images/on_boarding_images/
      - assets/images/welcome_images/


  uses-material-design: true

